extends Spatial

var morae = load("res://tenniscourts/morae.tscn")
#var morae2 = load("res://tenniscourts/morae2.tscn")

var mr = null

func _ready():
	randomize()

	for i in range(12):
		yield(get_tree().create_timer(rand_range(30, 60)), "timeout")
		mr = morae.instance()
#		rstone.set_param(preset_grps[0][randi()%4])
#		rstone.set_color(preset_colors[0])
		mr.set_preset(i+1)
		mr.audible_range_max = 130
		mr.translate(Vector3(rand_range(30, 100), 20, rand_range(-30,-70)))
		add_child(mr)

#
#	yield(get_tree().create_timer(10.0), "timeout")
#	for i in range(1):
#		var mr2 = morae2.instance()
##		rstone.set_param(preset_grps[0][randi()%4])
##		rstone.set_color(preset_colors[0])
#		mr2.set_preset(1)
#		mr2.audible_range_max = 120
#		mr2.translate(Vector3(rand_range(0, 0), 20, rand_range(0, 0)))
#		add_child(mr2)
##
#	yield(get_tree().create_timer(10.0), "timeout")
#	mr.set_rev(3)




